In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.65324063, 0.97146608, 0.5783551 , 0.29142837, 0.59190609])

In [22]:
np.random.rand(5,5)

array([[0.32527526, 0.43247911, 0.93320166, 0.45385394, 0.6500155 ],
       [0.81880138, 0.77408162, 0.50863177, 0.0569942 , 0.97081251],
       [0.727519  , 0.85341521, 0.04767051, 0.21483402, 0.80151898],
       [0.84347208, 0.7102733 , 0.44963776, 0.56807216, 0.89593188],
       [0.05739072, 0.11054024, 0.6482786 , 0.46502734, 0.05662895]])

In [23]:
np.random.randn(2)

array([ 0.32629206, -1.08274094])

In [24]:
np.random.randn(4,4)

array([[ 0.88691527,  0.89580122,  0.80593658, -0.53526618],
       [-0.94725438, -0.22023542, -0.68925382,  0.06029622],
       [ 0.88640697, -0.24179796,  0.72470006,  0.71540645],
       [ 0.68034124, -0.43906192,  0.12198041, -1.5851285 ]])

In [25]:
np.random.randint(1, 100)

75

In [26]:
np.random.randint(1, 100, 10)

array([13, 91,  1,  4, 50, 74, 42, 54, 69,  2])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
randarr = np.random.randint(0, 50, 10)

In [30]:
randarr

array([ 7, 27, 23, 45, 11, 36, 38, 14, 42, 10])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
randarr.max()

45

In [35]:
randarr.argmin()

0

In [37]:
randarr.argmax()

3

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

9